//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayTube.Languish {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayTube.Languish.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        internal static string Label_Add_comment {
            get {
                return ResourceManager.GetString("Label_Add_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Liked.
        /// </summary>
        internal static string Label_Add_The_Video_to_Liked {
            get {
                return ResourceManager.GetString("Label_Add_The_Video_to_Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video added.
        /// </summary>
        internal static string Label_Add_The_Videos_To_PlayList {
            get {
                return ResourceManager.GetString("Label_Add_The_Videos_To_PlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video added.
        /// </summary>
        internal static string Label_Add_The_Videos_to_watch_Later {
            get {
                return ResourceManager.GetString("Label_Add_The_Videos_to_watch_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to.
        /// </summary>
        internal static string Label_Add_to {
            get {
                return ResourceManager.GetString("Label_Add_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to play list.
        /// </summary>
        internal static string Label_Add_to_play_list {
            get {
                return ResourceManager.GetString("Label_Add_to_play_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watch later.
        /// </summary>
        internal static string Label_Add_to_watch_later {
            get {
                return ResourceManager.GetString("Label_Add_to_watch_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string Label_ALL {
            get {
                return ResourceManager.GetString("Label_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a User Login now.
        /// </summary>
        internal static string Label_Already_a_User_Login_now {
            get {
                return ResourceManager.GetString("Label_Already_a_User_Login_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars &amp; Vehicles.
        /// </summary>
        internal static string Label_Cars_Vehicles {
            get {
                return ResourceManager.GetString("Label_Cars_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Label_Categories {
            get {
                return ResourceManager.GetString("Label_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed Channels .
        /// </summary>
        internal static string Label_Channel_Subscribed {
            get {
                return ResourceManager.GetString("Label_Channel_Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection.
        /// </summary>
        internal static string Label_Check_Your_Internet {
            get {
                return ResourceManager.GetString("Label_Check_Your_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your action.
        /// </summary>
        internal static string Label_Choose_your_action {
            get {
                return ResourceManager.GetString("Label_Choose_your_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string Label_Comedy {
            get {
                return ResourceManager.GetString("Label_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Url.
        /// </summary>
        internal static string Label_Copy_Url {
            get {
                return ResourceManager.GetString("Label_Copy_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont have any videos.
        /// </summary>
        internal static string Label_Dont_have_any_videos {
            get {
                return ResourceManager.GetString("Label_Dont_have_any_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont worry type your email here and we will recover it for you..
        /// </summary>
        internal static string Label_Dont_worry_type_your_email {
            get {
                return ResourceManager.GetString("Label_Dont_worry_type_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Has Been Send.
        /// </summary>
        internal static string Label_Email_Has_Been_Send {
            get {
                return ResourceManager.GetString("Label_Email_Has_Been_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty PlayLists.
        /// </summary>
        internal static string Label_Empty_PlayLists {
            get {
                return ResourceManager.GetString("Label_Empty_PlayLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty search.
        /// </summary>
        internal static string Label_Empty_search {
            get {
                return ResourceManager.GetString("Label_Empty_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Subscribes.
        /// </summary>
        internal static string Label_Empty_Subscribes {
            get {
                return ResourceManager.GetString("Label_Empty_Subscribes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Videos.
        /// </summary>
        internal static string Label_Empty_Videos {
            get {
                return ResourceManager.GetString("Label_Empty_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string Label_Entertainment {
            get {
                return ResourceManager.GetString("Label_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Video.
        /// </summary>
        internal static string Label_Featured_Video {
            get {
                return ResourceManager.GetString("Label_Featured_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film &amp; Animation.
        /// </summary>
        internal static string Label_Film_Animation {
            get {
                return ResourceManager.GetString("Label_Film_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finsh.
        /// </summary>
        internal static string Label_Finsh {
            get {
                return ResourceManager.GetString("Label_Finsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Label_Forgot_your_password {
            get {
                return ResourceManager.GetString("Label_Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string Label_Gaming {
            get {
                return ResourceManager.GetString("Label_Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back and liked any video you.
        /// </summary>
        internal static string Label_Go_back_and_liked_any_video {
            get {
                return ResourceManager.GetString("Label_Go_back_and_liked_any_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back and Subscribe any channel you.
        /// </summary>
        internal static string Label_Go_back_and_Subscribe_any_channel_you {
            get {
                return ResourceManager.GetString("Label_Go_back_and_Subscribe_any_channel_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back and watched any video you.
        /// </summary>
        internal static string Label_Go_back_and_watched_any_video {
            get {
                return ResourceManager.GetString("Label_Go_back_and_watched_any_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Label_Header_Walkpage1 {
            get {
                return ResourceManager.GetString("Label_Header_Walkpage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats New ? .
        /// </summary>
        internal static string Label_Header_Walkpage2 {
            get {
                return ResourceManager.GetString("Label_Header_Walkpage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string Label_Header_Walkpage3 {
            get {
                return ResourceManager.GetString("Label_Header_Walkpage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Label_History {
            get {
                return ResourceManager.GetString("Label_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Videos.
        /// </summary>
        internal static string Label_History_Videos {
            get {
                return ResourceManager.GetString("Label_History_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-to &amp; Style.
        /// </summary>
        internal static string Label_How_to_Style {
            get {
                return ResourceManager.GetString("Label_How_to_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new video.
        /// </summary>
        internal static string Label_Import_new_video {
            get {
                return ResourceManager.GetString("Label_Import_new_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest videos.
        /// </summary>
        internal static string Label_Latest_videos {
            get {
                return ResourceManager.GetString("Label_Latest_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked Videos.
        /// </summary>
        internal static string Label_Liked_Videos {
            get {
                return ResourceManager.GetString("Label_Liked_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Label_Loading {
            get {
                return ResourceManager.GetString("Label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Not Correct, error Username Or Password.
        /// </summary>
        internal static string Label_Login_Not_Correct {
            get {
                return ResourceManager.GetString("Label_Login_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Label_More {
            get {
                return ResourceManager.GetString("Label_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Label_Music {
            get {
                return ResourceManager.GetString("Label_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Channel.
        /// </summary>
        internal static string Label_My_Channel {
            get {
                return ResourceManager.GetString("Label_My_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Politics.
        /// </summary>
        internal static string Label_News_Politics {
            get {
                return ResourceManager.GetString("Label_News_Politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Label_Next {
            get {
                return ResourceManager.GetString("Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos found for now!.
        /// </summary>
        internal static string Label_No_videos_found_for_now {
            get {
                return ResourceManager.GetString("Label_No_videos_found_for_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Videos to view.
        /// </summary>
        internal static string Label_no_Videos_to_view {
            get {
                return ResourceManager.GetString("Label_no_Videos_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-profits &amp; Activism.
        /// </summary>
        internal static string Label_Non_profits_Activism {
            get {
                return ResourceManager.GetString("Label_Non_profits_Activism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not interested.
        /// </summary>
        internal static string Label_Not_interested {
            get {
                return ResourceManager.GetString("Label_Not_interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Mode.
        /// </summary>
        internal static string Label_Offline_Mode {
            get {
                return ResourceManager.GetString("Label_Offline_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops it seems no videos on this category.
        /// </summary>
        internal static string Label_Oops_no_videos_by_this_category {
            get {
                return ResourceManager.GetString("Label_Oops_no_videos_by_this_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People &amp; Blogs.
        /// </summary>
        internal static string Label_People_Blogs {
            get {
                return ResourceManager.GetString("Label_People_Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets &amp; Animals.
        /// </summary>
        internal static string Label_Pets_Animals {
            get {
                return ResourceManager.GetString("Label_Pets_Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayLists.
        /// </summary>
        internal static string Label_PlayLists {
            get {
                return ResourceManager.GetString("Label_PlayLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayLists Videos.
        /// </summary>
        internal static string Label_PlayLists_Videos {
            get {
                return ResourceManager.GetString("Label_PlayLists_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email.
        /// </summary>
        internal static string Label_Please_Enter_Valid_Email {
            get {
                return ResourceManager.GetString("Label_Please_Enter_Valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to view comments.
        /// </summary>
        internal static string Label_please_login_to_view_your_comment {
            get {
                return ResourceManager.GetString("Label_please_login_to_view_your_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to view your subscriptions.
        /// </summary>
        internal static string Label_please_login_to_view_your_subscriptions {
            get {
                return ResourceManager.GetString("Label_please_login_to_view_your_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to add your Dislike .
        /// </summary>
        internal static string Label_Please_sign_in_Dislike {
            get {
                return ResourceManager.GetString("Label_Please_sign_in_Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to add your Like.
        /// </summary>
        internal static string Label_Please_sign_in_Liked {
            get {
                return ResourceManager.GetString("Label_Please_sign_in_Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to add to play list videos.
        /// </summary>
        internal static string Label_Please_sign_in_Playlist {
            get {
                return ResourceManager.GetString("Label_Please_sign_in_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to subscribe to the channel.
        /// </summary>
        internal static string Label_Please_sign_in_Subcribed {
            get {
                return ResourceManager.GetString("Label_Please_sign_in_Subcribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Label_Please_wait {
            get {
                return ResourceManager.GetString("Label_Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your full email address.
        /// </summary>
        internal static string Label_Please_Write_your_full_email {
            get {
                return ResourceManager.GetString("Label_Please_Write_your_full_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Label_Profile {
            get {
                return ResourceManager.GetString("Label_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Videos.
        /// </summary>
        internal static string Label_Random_Videos {
            get {
                return ResourceManager.GetString("Label_Random_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Label_Register {
            get {
                return ResourceManager.GetString("Label_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        internal static string Label_Register_now {
            get {
                return ResourceManager.GetString("Label_Register_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now and start watching videos.
        /// </summary>
        internal static string Label_Register_now_and_start_watching {
            get {
                return ResourceManager.GetString("Label_Register_now_and_start_watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Removed successfully.
        /// </summary>
        internal static string Label_Remove_Subcribed_Channel {
            get {
                return ResourceManager.GetString("Label_Remove_Subcribed_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove The Video To Liked.
        /// </summary>
        internal static string Label_Remove_The_Video_to_Liked {
            get {
                return ResourceManager.GetString("Label_Remove_The_Video_to_Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string Label_Repeat_Password {
            get {
                return ResourceManager.GetString("Label_Repeat_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Label_Retry {
            get {
                return ResourceManager.GetString("Label_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Random.
        /// </summary>
        internal static string Label_Search_Random {
            get {
                return ResourceManager.GetString("Label_Search_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Label_Security {
            get {
                return ResourceManager.GetString("Label_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEE ALL &gt;.
        /// </summary>
        internal static string Label_SEE_ALL {
            get {
                return ResourceManager.GetString("Label_SEE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Label_Send {
            get {
                return ResourceManager.GetString("Label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is invalid or expired you will be logout automatically, restart your application to login again.
        /// </summary>
        internal static string Label_Session_Dead {
            get {
                return ResourceManager.GetString("Label_Session_Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Label_Share {
            get {
                return ResourceManager.GetString("Label_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Label_Sign_up {
            get {
                return ResourceManager.GetString("Label_Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry I can not access.
        /// </summary>
        internal static string Label_Sorry_I_can_not_access {
            get {
                return ResourceManager.GetString("Label_Sorry_I_can_not_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string Label_Sports {
            get {
                return ResourceManager.GetString("Label_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start search.
        /// </summary>
        internal static string Label_Start_search {
            get {
                return ResourceManager.GetString("Label_Start_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed successfully.
        /// </summary>
        internal static string Label_Subcribed_Channel {
            get {
                return ResourceManager.GetString("Label_Subcribed_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Label_Subscribe {
            get {
                return ResourceManager.GetString("Label_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        internal static string Label_Subscribed {
            get {
                return ResourceManager.GetString("Label_Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string Label_Subscriptions {
            get {
                return ResourceManager.GetString("Label_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no subscriptions.
        /// </summary>
        internal static string Label_There_are_no_subscriptions {
            get {
                return ResourceManager.GetString("Label_There_are_no_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top videos.
        /// </summary>
        internal static string Label_Top_videos {
            get {
                return ResourceManager.GetString("Label_Top_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel &amp; Events.
        /// </summary>
        internal static string Label_Travel_Events {
            get {
                return ResourceManager.GetString("Label_Travel_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        internal static string Label_Trending {
            get {
                return ResourceManager.GetString("Label_Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again now.
        /// </summary>
        internal static string Label_Try_again_now {
            get {
                return ResourceManager.GetString("Label_Try_again_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up next.
        /// </summary>
        internal static string Label_Up_next {
            get {
                return ResourceManager.GetString("Label_Up_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Label_Upload {
            get {
                return ResourceManager.GetString("Label_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Copied.
        /// </summary>
        internal static string Label_Url_Copyed {
            get {
                return ResourceManager.GetString("Label_Url_Copyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to login.
        /// </summary>
        internal static string Label_Use_your_credentials_to_login {
            get {
                return ResourceManager.GetString("Label_Use_your_credentials_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Label_Videos {
            get {
                return ResourceManager.GetString("Label_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos by.
        /// </summary>
        internal static string Label_Videos_by {
            get {
                return ResourceManager.GetString("Label_Videos_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Label_Videos_Categories {
            get {
                return ResourceManager.GetString("Label_Videos_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Search.
        /// </summary>
        internal static string Label_View_videos_random {
            get {
                return ResourceManager.GetString("Label_View_videos_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Label_Views {
            get {
                return ResourceManager.GetString("Label_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload, share and view videos.
        /// </summary>
        internal static string Label_Walkpage1 {
            get {
                return ResourceManager.GetString("Label_Walkpage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayLists, History, Watch Later.
        /// </summary>
        internal static string Label_Walkpage2 {
            get {
                return ResourceManager.GetString("Label_Walkpage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch your videos filterd by categories.
        /// </summary>
        internal static string Label_Walkpage3 {
            get {
                return ResourceManager.GetString("Label_Walkpage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Later.
        /// </summary>
        internal static string Label_Watch_Later {
            get {
                return ResourceManager.GetString("Label_Watch_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Later Videos.
        /// </summary>
        internal static string Label_Watch_Later_Videos {
            get {
                return ResourceManager.GetString("Label_Watch_Later_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string Label_Welcome_to {
            get {
                return ResourceManager.GetString("Label_Welcome_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password Dont Match.
        /// </summary>
        internal static string Label_Your_Password_Dont_Match {
            get {
                return ResourceManager.GetString("Label_Your_Password_Dont_Match", resourceCulture);
            }
        }
    }
}
